export const easyQuestions = [
  {
    question: "Which team has won the most Premier League titles?",
    a: "Chelsea",
    b: "Manchester City",
    c: "Manchester United",
    d: "Liverpool",
    correct: "c",
  },
  {
    question: "What color is Liverpool’s home kit?",
    a: "Blue",
    b: "Red",
    c: "White",
    d: "Yellow",
    correct: "b",
  },
  {
    question: "Which team plays at Stamford Bridge?",
    a: "Arsenal",
    b: "Chelsea",
    c: "Tottenham",
    d: "West Ham",
    correct: "b",
  },
  {
    question: "Who is the all-time Premier League top scorer?",
    a: "Wayne Rooney",
    b: "Harry Kane",
    c: "Alan Shearer",
    d: "Sergio Agüero",
    correct: "c",
  },
  {
    question: "Which club is nicknamed The Gunners?",
    a: "Arsenal",
    b: "Tottenham",
    c: "Chelsea",
    d: "Manchester City",
    correct: "a",
  },
  {
    question: "What is Manchester United’s nickname?",
    a: "The Blues",
    b: "The Citizens",
    c: "The Reds",
    d: "The Red Devils",
    correct: "d",
  },
  {
    question: "Which city has both Manchester United and Manchester City?",
    a: "Liverpool",
    b: "London",
    c: "Manchester",
    d: "Birmingham",
    correct: "c",
  },
  {
    question: "Who is the current Liverpool manager (2025)?",
    a: "Pep Guardiola",
    b: "Mikel Arteta",
    c: "Jürgen Klopp",
    d: "Erik ten Hag",
    correct: "c",
  },
  {
    question:
      "Which team shocked the world by winning the 2015–16 Premier League?",
    a: "Chelsea",
    b: "Leicester City",
    c: "Manchester City",
    d: "Liverpool",
    correct: "b",
  },
  {
    question: "Which Liverpool legend was called ‘Captain Fantastic’?",
    a: "Steven Gerrard",
    b: "Robbie Fowler",
    c: "Jamie Carragher",
    d: "Michael Owen",
    correct: "a",
  },
];

export const mediumQuestions = [
  {
    question:
      "Who managed Manchester City when they won their first Premier League title (2011–12)?",
    a: "Pep Guardiola",
    b: "Roberto Mancini",
    c: "Manuel Pellegrini",
    d: "Sven-Göran Eriksson",
    correct: "b",
  },
  {
    question: "Who scored the famous last-minute winner vs QPR in 2012?",
    a: "Carlos Tévez",
    b: "Sergio Agüero",
    c: "Yaya Touré",
    d: "David Silva",
    correct: "b",
  },
  {
    question: "Who won the Premier League Golden Boot in 2022–23?",
    a: "Harry Kane",
    b: "Mohamed Salah",
    c: "Erling Haaland",
    d: "Marcus Rashford",
    correct: "c",
  },
  {
    question: "Which Premier League club has the motto ‘To Dare Is To Do’?",
    a: "Arsenal",
    b: "Chelsea",
    c: "Tottenham Hotspur",
    d: "Everton",
    correct: "c",
  },
  {
    question: "Which goalkeeper has the most Premier League clean sheets?",
    a: "David de Gea",
    b: "Edwin van der Sar",
    c: "Petr Čech",
    d: "Alisson",
    correct: "c",
  },
  {
    question: "Which player won PFA Player of the Year in 2019–20?",
    a: "Virgil van Dijk",
    b: "Sadio Mané",
    c: "Kevin De Bruyne",
    d: "Raheem Sterling",
    correct: "c",
  },
  {
    question: "Which two clubs contest the ‘Merseyside Derby’?",
    a: "Arsenal & Tottenham",
    b: "Chelsea & Fulham",
    c: "Liverpool & Everton",
    d: "Manchester United & Manchester City",
    correct: "c",
  },
  {
    question: "Who managed Arsenal during the ‘Invincibles’ 2003–04 season?",
    a: "Mikel Arteta",
    b: "Unai Emery",
    c: "Arsène Wenger",
    d: "George Graham",
    correct: "c",
  },
  {
    question: "Which player has the most assists in Premier League history?",
    a: "David Beckham",
    b: "Cesc Fàbregas",
    c: "Ryan Giggs",
    d: "Kevin De Bruyne",
    correct: "c",
  },
  {
    question: "Which team won the 2019–20 Premier League?",
    a: "Liverpool",
    b: "Manchester City",
    c: "Chelsea",
    d: "Manchester United",
    correct: "a",
  },
];

export const advancedQuestions = [
  {
    question:
      "Who scored the very first goal in Premier League history (1992)?",
    a: "Alan Shearer",
    b: "Brian Deane",
    c: "Eric Cantona",
    d: "Teddy Sheringham",
    correct: "b",
  },
  {
    question: "Which player was the first to reach 100 Premier League goals?",
    a: "Michael Owen",
    b: "Alan Shearer",
    c: "Les Ferdinand",
    d: "Thierry Henry",
    correct: "b",
  },
  {
    question:
      "Which club was relegated in the first Premier League season (1992–93)?",
    a: "Crystal Palace",
    b: "Middlesbrough",
    c: "Nottingham Forest",
    d: "Oldham Athletic",
    correct: "a",
  },
  {
    question:
      "Who is the only goalkeeper to have won the Premier League Player of the Season award?",
    a: "Petr Čech",
    b: "Edwin van der Sar",
    c: "Alisson",
    d: "Peter Schmeichel",
    correct: "d",
  },
  {
    question:
      "Which team conceded the most goals in a single Premier League season (100)?",
    a: "Swindon Town",
    b: "Derby County",
    c: "Fulham",
    d: "Barnsley",
    correct: "a",
  },
  {
    question: "Which player has scored the most Premier League hat-tricks?",
    a: "Sergio Agüero",
    b: "Thierry Henry",
    c: "Alan Shearer",
    d: "Harry Kane",
    correct: "a",
  },
  {
    question:
      "Which team had the lowest points total in Premier League history?",
    a: "Sunderland",
    b: "Derby County",
    c: "Huddersfield Town",
    d: "Norwich City",
    correct: "b",
  },
  {
    question: "Which manager has managed the most Premier League games?",
    a: "Arsène Wenger",
    b: "Sir Alex Ferguson",
    c: "David Moyes",
    d: "Harry Redknapp",
    correct: "a",
  },
  {
    question:
      "Who was the first African player to win the Premier League Golden Boot?",
    a: "Didier Drogba",
    b: "Emmanuel Adebayor",
    c: "Mohamed Salah",
    d: "Pierre-Emerick Aubameyang",
    correct: "a",
  },
  {
    question:
      "Which stadium has the highest capacity in the Premier League (2025)?",
    a: "Tottenham Hotspur Stadium",
    b: "Emirates Stadium",
    c: "Old Trafford",
    d: "Etihad Stadium",
    correct: "c",
  },
];
